In [1]:
import sys

# run this cell to install numpy
!{sys.executable} -m pip install numpy

# run this cell to install scipy
!{sys.executable} -m pip install scipy

In [12]:
import numpy as np

# Membuat Array di Numpy
L=np.array([3,7,1,5,8,2,7])

# Mean

In [13]:
# menghitung nilai mean menggunakan numpy
print("Data:",L)
print("Hasil Mean adalah:",np.mean(L))

Data: [3 7 1 5 8 2 7]
Hasil Mean adalah: 4.714285714285714


# Median

In [14]:
# Mencari nilai Median dari L
print("Data:",L)
print("Nilai Mediannya:",np.median(L))

Data: [3 7 1 5 8 2 7]
Nilai Mediannya: 5.0


# Modus

In [15]:
# fungsi ini digunakan untuk menyimpan angka yg unik

print("Data",L)
vals,counts = np.unique(L, return_counts=True)
index = np.argmax(counts)
print("Mode numpy:",vals[index])


# Finding Mode using Scipy

from scipy import stats
print("Mode scipy:",stats.mode(L))

Data [3 7 1 5 8 2 7]
Mode numpy: 7
Mode scipy: ModeResult(mode=array([7]), count=array([2]))


# Range

In [16]:
# Menghitung Range
print("Data ",L)
print("Range: ",L.max()-L.min())

Data  [3 7 1 5 8 2 7]
Range:  7


# Quartil dan Interquatil Range

In [17]:
# Mendefinisikan Data
dt=np.array([29,15,3,7,11,1,4,22])
print("Data:",dt)

# First quartile (Q1)
Q1 = np.quantile(dt, .25, interpolation = 'midpoint')
print("\nNilai dari Quartile 1:",Q1)
 
# Second quartile (Q2)
Q2 = np.quantile(dt, .50, interpolation = 'midpoint')
print("\nNilai dari Quartile 2:",Q2)

# Third quartile (Q3)
Q3 = np.quantile(dt, .75, interpolation = 'midpoint')
print("\nNilai dari Quartile 3:",Q3)

# Interquaritle range (IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR)

Data: [29 15  3  7 11  1  4 22]

Nilai dari Quartile 1: 3.5

Nilai dari Quartile 2: 9.0

Nilai dari Quartile 3: 18.5

Interquartile Range 15.0


C:\Users\MULAND~1\AppData\Local\Temp/ipykernel_8796/3498671847.py:6: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  Q1 = np.quantile(dt, .25, interpolation = 'midpoint')
C:\Users\MULAND~1\AppData\Local\Temp/ipykernel_8796/3498671847.py:10: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
  Q2 = np.quantile(dt, .50, interpolation = 'midpoint')
C:\Users\MULAND~1\AppData\Local\Temp/ipykernel_8796/3498671847.py:14: DeprecationWarning: the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are 

# Persentil

In [19]:
print("Data:",dt)
percentile_20 = np.percentile(dt,20)
print("20th Percentile:",round(percentile_20,2))

Data: [29 15  3  7 11  1  4 22]
20th Percentile: 3.4


# Varians dan Standar Deviasi

In [21]:
import numpy as np

dt=np.array([29,15,3,7,11,1,4,22])

print("Data",dt)

'''
    "Delta Degrees of Freedom": the divisor used in the calculation is
    ``N - ddof``, where ``N`` represents the number of elements. By
    default `ddof` is zero.
'''
print("Nilai dari Varains:",np.var(dt,ddof=1))
print("Nilai Standard Deviation:",np.std(dt,ddof=0)) # populasi
print("Nilai import numpy as np

Data [29 15  3  7 11  1  4 22]
Nilai dari Varains: 98.28571428571429
Nilai Standard Deviation: 9.273618495495704
Nilai Standard Deviation: 9.913915184512842


In [24]:
import statistics
j = [14,52,6,32,64,47,12,9,18,20]
k = [5,30,48,12,54,22,36,35,7,9]

# mean
print("Nilai rata-rata dari J yaitu: ", np.mean(j))

# range
print("Nilai rata-rata dari K yaitu :", np.max(k) - np.min(k))

# varians
print("Nilai Varians J :", np.var(j))

# Standart Deviasi
print("Nilai Standart Deviasi J: ", np.std(j)) # std populasi
print("Nilai Standart Deviasi K: ", statistics.stdev(k)) # std sampel, bisa pakai pst.dev untuk populasi

Nilai rata-rata dari J yaitu:  27.4
Nilai rata-rata dari K yaitu : 49
Nilai Varians J : 370.64
Nilai Standart Deviasi J:  19.252012881774206
Nilai Standart Deviasi K:  17.535994728304154


# Kovarians

In [25]:
j = np.array([1,3,5,7,11,9,13,17,15])
print(j)
k = np.array([2,4,6,8,12,10,14,20,18])
print(k)

print("\nCovariance ",np.cov(j,k)[0,1])

[ 1  3  5  7 11  9 13 17 15]
[ 2  4  6  8 12 10 14 20 18]

Covariance  33.5


# Korelasi

In [26]:
# mengembalikan matriks korelasi koefisie
print(np.corrcoef(j,k))

[[1.         0.99509828]
 [0.99509828 1.        ]]


# Kurtosis

In [27]:
dt1=np.linspace(-5,5,100)
print("Kurtosis",stats.kurtosis(dt1))

Kurtosis -1.2002400240024003


# Eigen Vektor

In [28]:
import numpy as np
b = np.matrix([[5,5,1],[6,2,4],[7,2,9]])
b

matrix([[5, 5, 1],
        [6, 2, 4],
        [7, 2, 9]])

In [33]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# membuat matriks baru yang merupakan transformasi linier dari x

c = b + 45*a
np.linalg.eig(b)

(array([13.46918929, -1.50753879,  4.03834949]),
 matrix([[ 0.37379875,  0.61264874, -0.56680661],
         [ 0.4736659 , -0.74406416, -0.05538347],
         [ 0.79744285, -0.26651463,  0.82198719]]))

In [35]:
np.linalg.eig(c)

(array([58.46918929, 43.49246121, 49.03834949]),
 matrix([[ 0.37379875,  0.61264874, -0.56680661],
         [ 0.4736659 , -0.74406416, -0.05538347],
         [ 0.79744285, -0.26651463,  0.82198719]]))